server:
  port: 8080

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/online_store?serverTimezone=UTC
      username: root
      password: 123

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
